"""add authentication settings

Revision ID: 00fb5b4c3463
Revises: d4249dca22a9
Create Date: 2026-08-24 14:48:08.961864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fb5b4c3463'
down_revision: Union[str, Sequence[str], None] = 'd4249dca22a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentication_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column(
        'open_registration',
        sa.Boolean(),
        server_default=sa.false(),
        nullable=False,
    ),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authentication_settings')
    # ### end Alembic commands ###
