"""add episode progress

Revision ID: 24a0bfc924b4
Revises: 84428be6f65e
Create Date: 2026-07-27 18:29:13.849965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a0bfc924b4'
down_revision: Union[str, Sequence[str], None] = '84428be6f65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('is_watched', sa.Boolean(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'episode_id', name='uq_episode_progress_user_id_episode_id')
    )
    with op.batch_alter_table('episode_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episode_progress_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_episode_progress_is_watched'), ['is_watched'], unique=False)
        batch_op.create_index(batch_op.f('ix_episode_progress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episode_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_episode_progress_is_watched'))
        batch_op.drop_index(batch_op.f('ix_episode_progress_episode_id'))

    op.drop_table('episode_progress')
    # ### end Alembic commands ###
