"""add data import runs

Revision ID: 301675778623
Revises: 3bf29b95c63a
Create Date: 2026-09-08 05:19:03.370081

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "301675778623"
down_revision: str | Sequence[str] | None = "3bf29b95c63a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_import_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "failed",
                name="data_import_run_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "phase",
            sa.Enum(
                "queued",
                "library_shows",
                "library_movies",
                "history_episodes",
                "history_movies",
                "finalizing",
                name="data_import_phase",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("progress_current", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("data_import_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_data_import_runs_user_status", ["user_id", "status"], unique=False
        )
        batch_op.create_index(
            "uq_data_import_runs_user_active",
            ["user_id"],
            unique=True,
            sqlite_where=sa.text("status IN ('queued', 'running')"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_import_runs", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_data_import_runs_user_active",
            sqlite_where=sa.text("status IN ('queued', 'running')"),
        )
        batch_op.drop_index("ix_data_import_runs_user_status")

    op.drop_table("data_import_runs")
    # ### end Alembic commands ###
