"""add movies to library

Revision ID: 3a60c4e4f349
Revises: 6ff812665b58
Create Date: 2026-08-08 00:55:29.521123

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a60c4e4f349"
down_revision: str | Sequence[str] | None = "6ff812665b58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("library_entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("movie_id", sa.Uuid(), nullable=True))
        batch_op.alter_column("show_id", existing_type=sa.CHAR(length=32), nullable=True)
        batch_op.create_index(batch_op.f("ix_library_entries_movie_id"), ["movie_id"], unique=False)
        batch_op.create_unique_constraint(
            "uq_library_entries_user_id_movie_id", ["user_id", "movie_id"]
        )
        batch_op.create_check_constraint(
            "ck_library_entries_single_media_target",
            """
            (
                show_id IS NOT NULL
                AND movie_id IS NULL
            )
            OR
            (
                show_id IS NULL
                AND movie_id IS NOT NULL
            )
            """,
        )

        batch_op.create_foreign_key(
            "fk_library_entries_movie_id_movies",
            "movies",
            ["movie_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("library_entries", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint("uq_library_entries_user_id_movie_id", type_="unique")
        batch_op.drop_index(batch_op.f("ix_library_entries_movie_id"))
        batch_op.alter_column("show_id", existing_type=sa.CHAR(length=32), nullable=False)
        batch_op.drop_column("movie_id")
        batch_op.drop_constraint(
            "ck_library_entries_single_media_target",
            type_="check",
        )
        batch_op.drop_constraint(
            "fk_library_entries_movie_id_movies",
            type_="foreignkey",
        )

    # ### end Alembic commands ###
