"""create shows and show genres

Revision ID: 3c7fa1f427e1
Revises: 6c805142447a
Create Date: 2026-07-22 06:19:29.119384

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c7fa1f427e1"
down_revision: str | Sequence[str] | None = "6c805142447a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=False),
        sa.Column("tvdb_id", sa.Integer(), nullable=True),
        sa.Column("imdb_id", sa.String(length=20), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("original_title", sa.String(length=255), nullable=False),
        sa.Column("overview", sa.Text(), nullable=False),
        sa.Column("tagline", sa.String(length=500), nullable=False),
        sa.Column("first_air_date", sa.Date(), nullable=True),
        sa.Column("last_air_date", sa.Date(), nullable=True),
        sa.Column("poster_path", sa.String(length=255), nullable=True),
        sa.Column("backdrop_path", sa.String(length=255), nullable=True),
        sa.Column("poster_cache_path", sa.String(length=500), nullable=True),
        sa.Column("backdrop_cache_path", sa.String(length=500), nullable=True),
        sa.Column("homepage_url", sa.String(length=2048), nullable=True),
        sa.Column("original_language", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("show_type", sa.String(length=100), nullable=False),
        sa.Column("in_production", sa.Boolean(), nullable=False),
        sa.Column("number_of_seasons", sa.Integer(), nullable=False),
        sa.Column("number_of_episodes", sa.Integer(), nullable=False),
        sa.Column("episode_run_time", sa.Integer(), nullable=True),
        sa.Column("popularity", sa.Float(), nullable=False),
        sa.Column("vote_average", sa.Float(), nullable=False),
        sa.Column("vote_count", sa.Integer(), nullable=False),
        sa.Column("metadata_language", sa.String(length=10), nullable=False),
        sa.Column(
            "metadata_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shows", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shows_imdb_id"), ["imdb_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_shows_title"), ["title"], unique=False)
        batch_op.create_index(batch_op.f("ix_shows_tmdb_id"), ["tmdb_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_shows_tvdb_id"), ["tvdb_id"], unique=True)

    op.create_table(
        "show_genres",
        sa.Column("show_id", sa.Uuid(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["show_id"], ["shows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("show_id", "genre_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("show_genres")
    with op.batch_alter_table("shows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shows_tvdb_id"))
        batch_op.drop_index(batch_op.f("ix_shows_tmdb_id"))
        batch_op.drop_index(batch_op.f("ix_shows_title"))
        batch_op.drop_index(batch_op.f("ix_shows_imdb_id"))

    op.drop_table("shows")
    # ### end Alembic commands ###
