"""add tmdb id to genres

Revision ID: 4db5fae196ad
Revises: f75835d7a747
Create Date: 2026-07-23 05:47:30.554258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db5fae196ad'
down_revision: Union[str, Sequence[str], None] = 'f75835d7a747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_genres_tmdb_id'), ['tmdb_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genres_tmdb_id'))
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###
