"""add seasons table

Revision ID: 529434c3d531
Revises: 4db5fae196ad
Create Date: 2026-07-24 22:44:11.476565

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "529434c3d531"
down_revision: str | Sequence[str] | None = "4db5fae196ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seasons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("show_id", sa.Uuid(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column("episode_count", sa.Integer(), nullable=False),
        sa.Column("vote_average", sa.Float(), nullable=False),
        sa.Column("tmdb_poster_path", sa.String(length=500), nullable=True),
        sa.Column("local_poster_path", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("episode_count >= 0", name="ck_seasons_episode_count_non_negative"),
        sa.CheckConstraint("season_number >= 0", name="ck_seasons_season_number_non_negative"),
        sa.CheckConstraint(
            "vote_average >= 0 AND vote_average <= 10", name="ck_seasons_vote_average_range"
        ),
        sa.ForeignKeyConstraint(["show_id"], ["shows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("show_id", "season_number", name="uq_seasons_show_id_season_number"),
    )
    with op.batch_alter_table("seasons", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_seasons_show_id"), ["show_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_seasons_tmdb_id"), ["tmdb_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seasons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_seasons_tmdb_id"))
        batch_op.drop_index(batch_op.f("ix_seasons_show_id"))

    op.drop_table("seasons")
    # ### end Alembic commands ###
