"""create genres table

Revision ID: 6c805142447a
Revises:
Create Date: 2026-07-17 17:42:54.524224

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c805142447a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("genres", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_genres_name"), ["name"], unique=True)
        batch_op.create_index(batch_op.f("ix_genres_slug"), ["slug"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("genres", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_genres_slug"))
        batch_op.drop_index(batch_op.f("ix_genres_name"))

    op.drop_table("genres")
    # ### end Alembic commands ###
