"""add episodes

Revision ID: 77d66e60c5d9
Revises: 529434c3d531
Create Date: 2026-07-26 12:42:36.528993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d66e60c5d9'
down_revision: Union[str, Sequence[str], None] = '529434c3d531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('tmdb_still_path', sa.String(length=500), nullable=True),
    sa.Column('local_still_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('episode_number >= 0', name='ck_episodes_episode_number_non_negative'),
    sa.CheckConstraint('runtime IS NULL OR runtime >= 0', name='ck_episodes_runtime_non_negative'),
    sa.CheckConstraint('vote_average >= 0 AND vote_average <= 10', name='ck_episodes_vote_average_range'),
    sa.CheckConstraint('vote_count >= 0', name='ck_episodes_vote_count_non_negative'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'episode_number', name='uq_episodes_season_id_episode_number')
    )
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodes_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_tmdb_id'), ['tmdb_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodes_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_episodes_season_id'))

    op.drop_table('episodes')
    # ### end Alembic commands ###
