"""add library entries

Revision ID: 84428be6f65e
Revises: cd36b6e5bb22
Create Date: 2026-07-27 07:24:40.496478

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84428be6f65e"
down_revision: str | Sequence[str] | None = "cd36b6e5bb22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("is_local", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "library_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("show_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planning",
                "watching",
                "completed",
                "paused",
                "dropped",
                name="library_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating IS NULL OR (rating >= 0 AND rating <= 10)",
            name="ck_library_entries_rating_range",
        ),
        sa.ForeignKeyConstraint(["show_id"], ["shows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "show_id", name="uq_library_entries_user_id_show_id"),
    )
    with op.batch_alter_table("library_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_library_entries_show_id"), ["show_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_library_entries_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_library_entries_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("library_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_library_entries_user_id"))
        batch_op.drop_index(batch_op.f("ix_library_entries_status"))
        batch_op.drop_index(batch_op.f("ix_library_entries_show_id"))

    op.drop_table("library_entries")
    op.drop_table("users")
    # ### end Alembic commands ###
