"""create genre provider mappings

Revision ID: 9c5224fb40cc
Revises: e526707222c5
Create Date: 2026-08-10 12:06:09.478330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5224fb40cc'
down_revision: Union[str, Sequence[str], None] = 'e526707222c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_provider_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('provider_genre_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'media_type', 'provider_genre_id', name='uq_genre_provider_mapping')
    )
    with op.batch_alter_table('genre_provider_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genre_provider_mappings_genre_id'), ['genre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_genre_provider_mappings_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_genre_provider_mappings_provider'), ['provider'], unique=False)

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genres_tmdb_id'))
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.INTEGER(), nullable=False))
        batch_op.create_index(batch_op.f('ix_genres_tmdb_id'), ['tmdb_id'], unique=1)

    with op.batch_alter_table('genre_provider_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genre_provider_mappings_provider'))
        batch_op.drop_index(batch_op.f('ix_genre_provider_mappings_media_type'))
        batch_op.drop_index(batch_op.f('ix_genre_provider_mappings_genre_id'))

    op.drop_table('genre_provider_mappings')
    # ### end Alembic commands ###
