"""backfill episode watch events

Revision ID: b333f3d8adad
Revises: 1fcb1074a10c
Create Date: 2026-08-14

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b333f3d8adad"
down_revision: Union[str, Sequence[str], None] = "1fcb1074a10c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Backfill historical watch events from existing Episode progress."""

    connection = op.get_bind()

    episode_progress = sa.table(
        "episode_progress",
        sa.column("user_id", sa.Uuid()),
        sa.column("episode_id", sa.Uuid()),
        sa.column("is_watched", sa.Boolean()),
        sa.column("watched_at", sa.DateTime(timezone=True)),
    )

    episode_watch_events = sa.table(
        "episode_watch_events",
        sa.column("id", sa.Uuid()),
        sa.column("user_id", sa.Uuid()),
        sa.column("episode_id", sa.Uuid()),
        sa.column("watched_at", sa.DateTime(timezone=True)),
    )

    watched_progress_rows = connection.execute(
        sa.select(
            episode_progress.c.user_id,
            episode_progress.c.episode_id,
            episode_progress.c.watched_at,
        ).where(
            episode_progress.c.is_watched.is_(True),
            episode_progress.c.watched_at.is_not(None),
        )
    ).all()

    for user_id, episode_id, watched_at in watched_progress_rows:
        existing_event = connection.execute(
            sa.select(
                episode_watch_events.c.id,
            )
            .where(
                episode_watch_events.c.user_id == user_id,
                episode_watch_events.c.episode_id == episode_id,
                episode_watch_events.c.watched_at == watched_at,
            )
            .limit(1)
        ).first()

        if existing_event is not None:
            continue

        connection.execute(
            episode_watch_events.insert().values(
                id=uuid4(),
                user_id=user_id,
                episode_id=episode_id,
                watched_at=watched_at,
            )
        )


def downgrade() -> None:
    """Do not remove watch events because their origin cannot be distinguished safely."""

    # Intentionally left empty.
    #
    # Once EpisodeWatchEvent rows exist, we cannot reliably distinguish:
    #
    # - rows generated by this backfill;
    # - rows created naturally by the application.
    #
    # Deleting rows during downgrade could therefore destroy real
    # historical viewing data.
    pass