"""add movie watch events

Revision ID: bff6998b9c5d
Revises: b333f3d8adad
Create Date: 2026-08-17 04:45:35.611176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff6998b9c5d'
down_revision: Union[str, Sequence[str], None] = 'b333f3d8adad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_watch_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movie_watch_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_watch_events_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index('ix_movie_watch_events_user_id_movie_id', ['user_id', 'movie_id'], unique=False)
        batch_op.create_index('ix_movie_watch_events_user_id_watched_at', ['user_id', 'watched_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_watch_events', schema=None) as batch_op:
        batch_op.drop_index('ix_movie_watch_events_user_id_watched_at')
        batch_op.drop_index('ix_movie_watch_events_user_id_movie_id')
        batch_op.drop_index(batch_op.f('ix_movie_watch_events_movie_id'))

    op.drop_table('movie_watch_events')
    # ### end Alembic commands ###
