"""add users

Revision ID: cd36b6e5bb22
Revises: 77d66e60c5d9
Create Date: 2026-07-27 06:32:55.294970

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "cd36b6e5bb22"
down_revision: str | Sequence[str] | None = "77d66e60c5d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
