"""add networks

Revision ID: d2a14cc25721
Revises: 24a0bfc924b4
Create Date: 2026-07-28 04:45:01.228969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a14cc25721'
down_revision: Union[str, Sequence[str], None] = '24a0bfc924b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tmdb_logo_path', sa.String(length=500), nullable=True),
    sa.Column('origin_country', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('networks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_networks_tmdb_id'), ['tmdb_id'], unique=True)

    op.create_table('show_networks',
    sa.Column('show_id', sa.Uuid(), nullable=False),
    sa.Column('network_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('show_id', 'network_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_networks')
    with op.batch_alter_table('networks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_networks_tmdb_id'))

    op.drop_table('networks')
    # ### end Alembic commands ###
