"""update show metadata and image paths

Revision ID: f75835d7a747
Revises: 3c7fa1f427e1
Create Date: 2026-07-23 04:53:11.828301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75835d7a747'
down_revision: Union[str, Sequence[str], None] = '3c7fa1f427e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_poster_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('tmdb_backdrop_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('local_poster_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('local_backdrop_path', sa.String(length=500), nullable=True))
        batch_op.alter_column('overview',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('tagline',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('metadata_language',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('backdrop_cache_path')
        batch_op.drop_column('backdrop_path')
        batch_op.drop_column('poster_cache_path')
        batch_op.drop_column('poster_path')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('poster_cache_path', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('backdrop_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('backdrop_cache_path', sa.VARCHAR(length=500), nullable=True))
        batch_op.alter_column('metadata_language',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('tagline',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('overview',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('local_backdrop_path')
        batch_op.drop_column('local_poster_path')
        batch_op.drop_column('tmdb_backdrop_path')
        batch_op.drop_column('tmdb_poster_path')

    # ### end Alembic commands ###
